# Generated by Django 3.1.2 on 2020-10-16 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oeta', '0002_auto_20201016_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exampaper',
            options={'ordering': ('title',), 'verbose_name_plural': 'Exam Papers'},
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
    ]
