# Generated by Django 3.1.2 on 2020-10-15 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oeta', '0002_choice_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('title', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('title', 'subject')},
        ),
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('questions', smart_selects.db_fields.ChainedManyToManyField(chained_field='subject', chained_model_field='subject', horizontal=True, to='oeta.Question', verbose_name='questions')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oeta.subject')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Exam_Papers',
                'db_table': 'exam_papers',
                'ordering': ('title',),
                'unique_together': {('title', 'subject')},
            },
        ),
    ]
