# Generated by Django 3.1.2 on 2020-10-18 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oeta', '0005_auto_20201019_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaperSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.CharField(blank=True, max_length=1, null=True)),
                ('exam_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oeta.exampaper')),
            ],
            options={
                'verbose_name_plural': 'Exam Paper Sets',
                'db_table': 'exam_paper_sets',
                'ordering': ('exam_paper',),
                'unique_together': {('exam_paper', 'set')},
            },
        ),
    ]
