# Generated by Django 3.1.2 on 2020-10-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oeta', '0006_exampaperset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampaper',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='oeta.Student'),
        ),
    ]
