# Generated by Django 3.1.2 on 2020-10-18 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oeta', '0007_auto_20201019_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaperset',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oeta.question'),
        ),
    ]
